Implemented stack
1c3t3a/rust-data-structures pull request #20
Opened 2020-10-01 05:11 UTC by 1c3t3a

Closes #9.

2020-10-01 05:11 UTC, 1c3t3a commented
# [Codecov](https://codecov.io/gh/1c3t3a/rust-data-structures/pull/20?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`master@3fe702e`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `n/a`.

[![Impacted file tree graph](https://codecov.io/gh/1c3t3a/rust-data-structures/pull/20/graphs/tree.svg?width=650&height=150&src=pr&token=2U3SO11CMH)](https://codecov.io/gh/1c3t3a/rust-data-structures/pull/20?src=pr&el=tree)

```diff
@@            Coverage Diff            @@
##             master      #20   +/-   ##
=========================================
  Coverage          ?   96.28%           
=========================================
  Files             ?        2           
  Lines             ?      377           
  Branches          ?        0           
=========================================
  Hits              ?      363           
  Misses            ?       14           
  Partials          ?        0           
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/1c3t3a/rust-data-structures/pull/20?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/1c3t3a/rust-data-structures/pull/20?src=pr&el=footer). Last update [3fe702e...bd4610d](https://codecov.io/gh/1c3t3a/rust-data-structures/pull/20?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

2020-10-06 13:58 UTC, Colin1860 requested changes

2020-10-06 13:58 UTC, Colin1860 commented on src/stack.rs
> +
Suggestion: Think about implementing the Default trait

2020-10-06 13:58 UTC, Colin1860 commented on src/stack.rs
> +    fn size(&self) -> i32 {
I'm not happy with a non storing size function here tbh, could you store the size in a variable pls

2020-10-06 13:58 UTC, Colin1860 commented on src/stack.rs
> +    fn size(&self) -> i32 {
Imagine a stack with 10000+ elements, the size-method does not scale and all just for adding numbers. Do you know what i mean?

2020-10-06 13:58 UTC, Colin1860 commented on src/stack.rs
> +
If you'd be up for it, you could implement the from trait for the linked list: linkedlist -> stack so to speak

2020-10-11 13:00 UTC, merged